//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMCS_WPF_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Claim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Claim()
        {
            this.SupportingDocuments = new HashSet<SupportingDocument>();
        }
    
        public int ClaimID { get; set; }
        public Nullable<int> LecturerID { get; set; }
        public Nullable<decimal> HoursWorked { get; set; }
        public Nullable<decimal> HourlyRate { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> DateSubmitted { get; set; }
    
        public virtual Lecturer Lecturer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupportingDocument> SupportingDocuments { get; set; }
    }
}
