//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMCS_WPF_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupportingDocument
    {
        public int DocumentID { get; set; }
        public Nullable<int> ClaimID { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
    
        public virtual Claim Claim { get; set; }
    }
}
